Repository incubateur-ademe/nosgestesclimat, pull requests merged in 2023-04, with the labels that each got.

#1794 Feat(scripts/build): support publicodes model packages
  data/transport/transport . ferry.yaml
  docs/Publicodes.md
  docs/_Sidebar.md
  package.json
  scripts/getModelFromSource.js
  scripts/i18n/check-translation.js
  scripts/i18n/cli.js
  scripts/i18n/translate-rules.js
  scripts/rulesToJSON.mjs
  yarn.lock
Labels: tech

#1761 Swiss average flight, french and english
  data/i18n/models/CH-en-us.yaml
  data/i18n/models/CH-fr.yaml
Labels: contribution externe, i18n

#1818 Feat(script/build): parallelizes the model compilation
  package.json
  scripts/modelOptim.mjs
  scripts/rulesToJSON.mjs
  scripts/rulesToJSON.worker.mjs
  yarn.lock
Labels: tech

#1806 Create TN-fr.yaml
  data/i18n/models/TN-en-us.yaml
  data/i18n/models/TN-fr.yaml
  package.json
  scripts/i18n/addRegionToBaseRules.js
  scripts/i18n/regionCommons.js
  scripts/modelOptim.mjs
  scripts/rulesToJSON.mjs
Labels: tech, contribution externe, i18n

#1851 CI: break the workflow if an error occured in the rule compilation/optimisation pass
  .github/workflows/upload-compilation-result.yaml
  scripts/rulesToJSON.mjs
  scripts/rulesToJSON.worker.mjs
Labels: tech

#1852 feat(scripts/i18n): add 'all' option to remove all not up to date rule translations
  scripts/i18n/check-translation.js
  scripts/i18n/cli.js
Labels: tech, t9n
